# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivers',
            old_name='phone_number',
            new_name='id_number',
        ),
    ]
