# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0002_auto_20171004_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
