# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0003_drivers_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='phone_number',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
