# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0004_auto_20171005_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
