# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0005_auto_20171005_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivers',
            name='user',
        ),
    ]
