# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ussd', '0006_remove_drivers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
