# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0004_auto_20171002_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='entities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to=settings.AUTH_USER_MODEL),
        ),
    ]
