# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_userprofile_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Insurance', 'Insurance Company'), ('Sacco', 'Sacco'), ('Matatu', 'Matatu Owner')], max_length=200, null=True),
        ),
    ]
