# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20171005_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanValidationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=200, null=True)),
                ('registration_number', models.CharField(max_length=200, null=True)),
                ('route_number', models.CharField(max_length=200, null=True)),
                ('from_location', models.CharField(max_length=200, null=True)),
                ('to_location', models.CharField(max_length=200, null=True)),
                ('start_time', models.CharField(max_length=200, null=True)),
                ('end_time', models.CharField(max_length=200, null=True)),
                ('event_type', models.CharField(max_length=200, null=True)),
                ('event_description', models.CharField(max_length=200, null=True)),
                ('fare', models.CharField(max_length=200, null=True)),
                ('passengers', models.CharField(max_length=200, null=True)),
                ('exact_time', models.CharField(max_length=200, null=True)),
                ('latitude', models.CharField(max_length=200, null=True)),
                ('longitude', models.CharField(max_length=200, null=True)),
                ('altitude', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
