# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_auto_20171009_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_v_max', models.CharField(max_length=200, null=True)),
                ('acc_l_max', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
