# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_sensordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='cluster',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
